version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MentorFileUploader"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jk12rud8xwju"
s3_prefix = "MentorFileUploader"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
